### ISSUE TITLE
Enable gpu execution

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-whisper-wrapper#12]
### Because

When `model=large`, Whisper is extremely slow when running on CPU-only.

### Done when

When a user runs whisper-wrapper with parameter `device=cuda` Whisper runs on the machine's GPU instead of CPU.

If it is not possible to choose gpu or cpu as a parameter sent to the web service, it would still be fine (though less desirable) to have a separate app or version with gpu support enabled.

### Additional context

Chowda is already configured to use CUDA.

**Comment by owencking** [comment]
Cool.  Thanks.  We'll see if we can get that working.

**Comment by keighrim** [comment]
This might be a better reference to install helpers on Windows: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by keighrim** [comment]
closing as non-issue
