### ISSUE TITLE
Add language parameter for Whisper ASR

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-whisper-wrapper#17]
### Because

Whisper can autodetect the language for transcription.  However, for some assets the autodetection is unreliable.  For those, Whisper performance will be better if the language can be passed to whisper-wrapper as the value of a parameter.

The language should be specified by the user with a string conforming to [best current practice defined by IETF RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) and mapped to one of the [languages supported by Whisper](https://github.com/openai/whisper/blob/main/whisper/tokenizer.py).

### Done when

Main requirements:
- User can specify language via a parameter.
- Language selection is internally passed to Whisper for the ASR process.
- User's language parameter is recorded in MMIF output in `parameters`.
- The language parameter is recorded also in the `TextDocument`'s `@language` value.

**Comment by owencking** [comment]
The app seems to interpret the `modelLang` parameter in a way that causes problems with certain models.

The desired behavior is that the language parameter be used so that the language does not have to be auto-detected.  I can't tell whether this is happening.  

Regardless, the language parameter is also being appended to the model name.  This is valid only for some models.  So, for example, if the app is run with the `model=turbo` and `modelLang=en`, then since there is no English-only version of the turbo model, the following error occurs:

```
Traceback (most recent call last):
  File "cli.py", line 88, in <module>
    out_mmif = clamsapp.annotate(in_data, **params)
  File "/usr/local/lib/python3.8/site-packages/clams/app/__init__.py", line 151, in annotate
    annotated = self._annotate(mmif, **refined)
  File "/app/app.py", line 72, in _annotate
    self.whisper_models[size] = whisper.load_model(size)
  File "/usr/local/lib/python3.8/site-packages/whisper/__init__.py", line 143, in load_model
    raise RuntimeError(
RuntimeError: Model turbo.en not found; available models = ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large', 'large-v3-turbo', 'turbo']
```

**Comment by owencking** [comment]
I am wondering more about this issue.  I actually think there are two conceptually distinct parameters.  One is the **model language** as with models that have English-only variants, such as `tiny.en`.  A different parameter is the language in which to perform transcription (as opposed to auto-detecting the language).  I would call this the **transcription language** or maybe the **target language**.  

The current documentation for this app suggests that `modelLang` is the model language, not the transcription language. 

I think it should be possible to set those parameters independently.  In particular, it should be possible to set the transcription language to English, but still use the multilingual version of `tiny`, `base`, `small`, or `medium`, right?

Is there currently no way to set the transcription language?

**Comment by Brendayy** [comment]
For large and turbo, `modelLang` is where you set up the **transcription language**. When it is not empty, whisper will bypass language detection and transcribe that language. https://apps.clams.ai/whisper-wrapper/v13/. 

> I think it should be possible to set those parameters independently. In particular, it should be possible to set the transcription language to English, but still use the multilingual version of `tiny`, `base`, `small`, or `medium`, right?

You are right, I just checked again. I would need to add an extra parameter so that you can force English with multilingual version of smaller models.

**Comment by owencking** [comment]
Some more thoughts about this...  

I'm looking for something both at the **level of functionality** and at the **level of documentation**.

At the level of functionality, I would like to be able to choose "en" as my transcription language, but still be able to select `small` or `small.en` according to my preference.  The reason is that, even if `small.en` has better "overall" performance, it might be worse in some says.  For example, perhaps it performs worse on predicting the spelling of non-Western names or something.  We shouldn't rule this out.

At the level of documentation, I would like a single key-value pair in the MMIF that unambiguously indicates what inference model was being used.  In the [current draft of transcript provenance metadata](https://docs.google.com/document/d/1dIJbvaySKgJHiNOorqIMV89tjz0caEEjt3HzNqpMtbk), we have an element called "inference_model" to record this.  If the value of `modelSize` is "small", it is unclear whether the value for this element should be `small` or `small.en`, and I need extra logic specific to whisper-wrapper to figure out the model.

As I said before, my preferred solution is to have separate arguments for the inference model (for which the value could be "small" or "small.en") and for the intended output language.
