### ISSUE TITLE
missing documentation on how-to-run

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-whisper-wrapper#2]
I was talking to @Brendayy today and found that this repository is missing any documentation about the installation and operation of the app. @eholderness95 can you add something that @Brendayy can use to start running whisper on AAPB data for the LoC slide material?

**Comment by eholderness95** [comment]
Yes, thanks for reminder! Will do that today.

**Comment by eholderness95** [comment]
Added minimal start to ReadMe
