### ISSUE TITLE
analyzer license is wrong

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-whisper-wrapper#3]
Current app metadata says the analyzer (whisper) license [is unknown](https://github.com/clamsproject/app-whisper-wrapper/blob/main/app.py#L31) but in fact, the whisper is [licensed under MIT](https://github.com/openai/whisper/blob/main/LICENSE).

**Comment by eholderness95** [comment]
What is the proper way of writing an MIT license in string notation? Just "MIT" ? The reason it is currently set as unknown is that's what the Kaldi wrapper has and I wasn't sure what to put there.

**Comment by keighrim** [comment]
Yeah, we haven't decided on any requirements for the license string format. Anything human can recognize should be enough for now.

**Comment by eholderness95** [comment]
Fixed in commit 34e5e78f79c543a22c9d0aa908df91eeb0ec139d
