### ISSUE TITLE
error with transcribing (with the default tiny model)

### ISSUE THREAD

**Issue by Brendayy** [clamsproject/app-whisper-wrapper#8]
#### This is potentially due to file path incorrectly redirected. I am trying to test it both locally and on server again now. Will close this if succeed.

Even though whisper image can be pulled on local machine, and an input.mmif can be successfully generated, the output.mmif has an error. The locally tested video file is **_cpb-aacip-122a5fd2dcc.mp4_**. from `child`

<img width="1290" alt="image" src="https://github.com/clamsproject/app-whisper-wrapper/assets/43281544/59ff3a15-6c66-4466-8b1c-b155c5d037c5">

**Comment by keighrim** [comment]
Just for the future, could you not upload screenshots, but instead copy and pates actual terminal text, so that other people can copy and paste from the report for testing? Thanks!

**Comment by keighrim** [comment]
I think b9a423a04e9f3bf9c89bef48343f2ab0473b6d41 should solved this problem. @Brendayy can you try again with `v3`, and see if the problem persists?

**Comment by Brendayy** [comment]
### update 7/24
After trying `v3` ([b9a423a](https://github.com/clamsproject/app-whisper-wrapper/commit/b9a423a04e9f3bf9c89bef48343f2ab0473b6d41)), ffmpeg error disappeared, but now with new error locating the video file after mapping the local directory to container. For example, I first run
```
podman run --name whisper_test -v /home/yangyangchen/sample_video:/data -p 5000:5000 --rm ghcr.io/clamsproject/app-whisper-wrapper:latest
```
assuming videos locate at `/home/yangyangchen/sample_video` on `child`.

after server is up, running:
```
clams source audio:/data/cpb-aacip-122a5fd2dcc.mp4 > cpb-aacip-122a5fd2dcc_input.mmif
curl -H "Accept: application/json" -X POST -d@cpb-aacip-122a5fd2dcc_input.mmif -s http://localhost:5000 > cpb-aacip-122a5fd2dcc.mmif
```
The error message is shown as:
<img width="1350" alt="image" src="https://github.com/clamsproject/app-whisper-wrapper/assets/43281544/fd88afb7-4fc9-4afb-ade4-279c09f53a6a">

**Comment by keighrim** [comment]
If the file is there in the directory for sure, it's probably file permission issue with rootless podman. Try `:z` or `:Z` suffix with the volume argument, e.g., `podman run ... -v /home/..../:/data:z ... `

**Comment by keighrim** [comment]
Closing as stale (and probably the error is caused from some ill-set container env).
